.Dd 6 May 2016
.Dt STATSITE 8
.Os LINUX
.Sh NAME
.Nm statsite
.Nd a C implemementation of Etsy statsd
.\"
.Sh SYNOPSIS
.Nm
collects data and sends it to a central server for processing.
.Pp
.Nm
statsite runs in the background as a daemon, and allows for use of various sinks to send collected data to the central storage server.
.\"
